name: serene
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.1.0
  bloc: ^9.0.0
  firebase_auth: ^6.0.2
  permission_handler: ^12.0.1
  async: ^2.13.0
  camera: ^0.11.2
  image_picker: ^1.2.0
  dash_chat_2: ^0.0.21
  flutter_bloc: ^9.1.1
  flutter_sound: ^9.28.0
  google_fonts: ^6.3.2
  go_router: ^16.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21